### ISSUE TITLE
Clear search section before adding a new note

### ISSUE THREAD

**Issue by Mentalchaos** [raerpo/mdnotes#22]
When you try to create a new note but you already have something write in the search section
example : 'test'

You wont be able to see the new notes because the search section is searching for another note (in this case your looking for 'test')

Notes are gonna be created but you cant see them if u dont clean the search field

so I recommend to clean the search field before making a new note and then make a new one when you click the (+) button

**Comment by raerpo** [comment]
Thanks for the bug report. I solve it in the latest release
